name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 2 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test Project

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: typos-action
      uses: crate-ci/typos@v1.31.1

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Check Formatting
      run: cargo fmt --all -- --check

    - name: Install dependencies
      run: sudo apt install -y protobuf-compiler

    - name: Cargo Cache
      uses: Swatinem/rust-cache@v2

    - name: Build project
      run: cargo build

    - name: Test project
      run: cargo test --all

    - name: Run clippy
      uses: giraffate/clippy-action@v1
      with:
        reporter: 'github-pr-check'
        clippy_flags: --workspace --no-deps
        filter_mode: nofilter
        github_token: ${{ secrets.GITHUB_TOKEN }}
